# Generated by Django 3.2.5 on 2022-02-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='user <django.db.models.fields.CharField>', max_length=50)),
                ('password', models.CharField(default='1234', max_length=32)),
                ('date_of_creat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
