# Generated by Django 3.2.5 on 2022-02-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220209_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='untitled', max_length=32)),
                ('describe', models.CharField(default='undescribe', max_length=1024)),
            ],
        ),
    ]
